src/BoilerPlateExample.Web/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoilerPlateExample.Dto;
using BoilerPlateExample.Dto.Device;
using BoilerPlateExample.Dto.Office;
using BoilerPlateExample.Interfaces;
using BoilerPlateExample.Web.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BoilerPlateExample.Web.Controllers
{
    public class DeviceController : BoilerPlateExampleControllerBase
    {
        private readonly IDeviceService _deviceService;

        protected readonly IEmployeeService _employeeService;

        public DeviceController(IDeviceService deviceService, IEmployeeService employeeService)
        {
            _deviceService = deviceService;
            _employeeService = employeeService;
        }

        //-------------- GET DEVICES/DEVICE -----------------//
        public IActionResult GetDevices()
        {
            var result = _deviceService.GetAll();
            return View(result);
        }

        [HttpGet]
        public IActionResult GetDevice(int? id)
        {
            DeviceGet device = null;
            if (id.HasValue)
            {
                device = _deviceService.Get(id.Value);
            }

            return View(device);
        }

        [HttpGet]
        public IActionResult GetDeviceHistory(int id)
        {
            var result = _deviceService.GetDeviceHistory(id);
            return View(result);
        }


        //------------ DROP DOWN EMPLOYEES --------------//
        public SelectList SelectEmployees()
        {
            var employeesForSelect = new EmployeeListDtoForSelect(_employeeService);

            var employees = employeesForSelect.Employees.Employees.ToList();

            var selectEmployees = employees.Select(x => new
            {
                Id = x.Id,
                FullName = x.FirstName + " " + x.LastName
            });

            SelectList selectList = new SelectList(selectEmployees, "Id", "FullName");

            return selectList;
        }


        //--------------- CREATE DEVICE -------------------//
        [HttpGet]
        public IActionResult CreateDevice()
        {
            var employees = SelectEmployees();
            ViewData["DropDown"] = employees;

            return View(new DevicePost());
        }

        [HttpPost]
        public IActionResult CreateDevice(DevicePost deviceDto)
        {

            _deviceService.Create(deviceDto);
            return RedirectToAction("GetDevices");

        }


        //---------------- DELETE DEVICE ----------------//
        [HttpPost]
        public IActionResult DeleteDevice(int id)
        {
            _deviceService.Delete(id);

            return RedirectToAction("GetDevices");
        }


        //-------------- UPDATE DEVICE -----------------//
        [HttpGet]
        public IActionResult UpdateDevice(int id)
        {
            var device = _deviceService.GetDeviceById(id);

            DevicePost newDevicePost = new DevicePost
            {
                Name = device.Name,
                EmployeeId = device.EmployeeId
            };

            var employees = SelectEmployees();
            ViewData["DropDown"] = employees;
            // ViewBag.DropDown = new SelectList(SelectOffices());

            return View(newDevicePost);
        }

        [HttpPost]
        public IActionResult UpdateDevice(int id, DevicePost dto)
        {
            _deviceService.Update(id, dto);

            return RedirectToAction("GetDevices");
        }


    }
}

src/BoilerPlateExample.Web/Views/Device/CreateDevice.cshtml
@model BoilerPlateExample.Dto.Device.DevicePost

@{
    ViewBag.Title = "Create new device";
    var list = ViewBag.DropDown as SelectList;
}

<h3>@ViewBag.Title</h3>

<form action="" method="post">

    @Html.HiddenFor(x => x.Id)
    <br />
    @Html.LabelFor(x => x.Name, "Name:")
    &nbsp;
    @Html.EditorFor(x => x.Name)
    <br />
    @Html.LabelFor(x => x.EmployeeId, "Employee:")
    &nbsp;
    @Html.DropDownListFor(x => x.EmployeeId, (IEnumerable<SelectListItem>)list, "-- Choose Employee --")
    <br />

    <input type="submit" value="Create Device" />

</form>

src/BoilerPlateExample.Web/Views/Device/GetDevice.cshtml
@model BoilerPlateExample.Dto.Device.DeviceGet

@{
    ViewBag.Title = "Device details";
}

<h3>@ViewBag.Title</h3>

@if (Model != null)
{
    @Html.TextBoxFor(x => x.Name)
    @Html.TextBoxFor(x => x.FirstName)
    @Html.TextBoxFor(x => x.LastName)

    @Html.ActionLink("History", "GetDeviceHistory", new { id = Model.Id })
}
else
{
    <form action="" method="get">

        @Html.LabelFor(x => x.Id, "Insert Id: ")
        &nbsp;
        @Html.EditorFor(x => x.Id)
        &nbsp;
        <input type="submit" value="Get Device Details" />

    </form>
}

src/BoilerPlateExample.Web/Views/Device/GetDeviceHistory.cshtml
@model BoilerPlateExample.Dto.Device.DeviceUsageHistoryDto

@{
    ViewBag.Title = "History";
}

<h4>ViewBag.Title</h4>

@foreach (var usage in @Model.UsageList)
{
    <div>
        @usage.FirstName &nbsp;@usage.LastName
        <br />
        @usage.From &nbsp; @usage.To
        <br/>
        <br/>
    </div>
}

src/BoilerPlateExample.Web/Views/Device/GetDevices.cshtml
@model BoilerPlateExample.Dto.Device.DeviceListDto

@{
    ViewBag.Title = "List Of Devices";
}

<h3>@ViewBag.Title</h3>

@foreach (var device in Model.Devices)
{
<div>
    @device.Name
    <br />
    @Html.ActionLink("Update", "UpdateDevice", new { id = device.Id })
    &nbsp;
    @Html.ActionLink("Details", "GetDevice", new { id = device.Id })
    <br/>
    @using (Html.BeginForm("DeleteDevice", "Device", new { id = device.Id }))
    {<button type="submit" name="Delete" onclick="return confirm('Are you sure you want to delete this device?')" value="Delete">Delete</button>}
</div>
}

<br/>
<h4>
    @Html.ActionLink("Add New", "CreateDevice")
</h4>

src/BoilerPlateExample.Web/Views/Device/UpdateDevice.cshtml
@model BoilerPlateExample.Dto.Device.DevicePost

@{
    ViewBag.Title = "Change Device Details";
    var list = ViewBag.DropDown as SelectList;
}

<h3>@ViewBag.Title</h3>

<form action="" method="post">
        
    @Html.HiddenFor(x => x.Id)
    <br />
    @Html.LabelFor(x => x.Name, "Name:")
    &nbsp;
    @Html.EditorFor(x => x.Name)
    <br />
    @Html.LabelFor(x => x.EmployeeId, "Employee:")
    &nbsp;
    @Html.DropDownListFor(x => x.EmployeeId, list, "-- Choose Employee --")


    <input type="submit" value="Update Device" />
</form>