src/BoilerPlateExample.Web/Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.UI.Inputs;
using BoilerPlateExample.Dto;
using BoilerPlateExample.Dto.Office;
using BoilerPlateExample.Models;
using BoilerPlateExample.Web.Views;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BoilerPlateExample.Web.Controllers
{
    public class OfficeController : BoilerPlateExampleControllerBase
    {
        private readonly IOfficeService _officeService;

        public OfficeController(IOfficeService officeService)
        {
            _officeService = officeService;
        }


        //-------------- GET OFFICES/OFFICE -----------------//
        public IActionResult GetOffices()
        {
            var result = _officeService.GetAll();
            var model = new OfficeListDto(result);
            return View(model);
        }


        [HttpGet]
        public IActionResult GetOffice(int? id)
        {
            OfficeEmployeeListDto office = null;
            if (id.HasValue)
            {
                office = _officeService.Get(id.Value);
            }

            return View(office);
        }


        //-------------- CREATE OFFICE -----------------//
        [HttpGet]
        public IActionResult CreateOffice()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateOffice(OfficeDto officeDto)
        {
            _officeService.Create(officeDto);
            return RedirectToAction("GetOffices");
        }


        //-------------- DELETE OFFICE -----------------//
        [HttpPost]
        public IActionResult DeleteOffice(int id)
        {
            _officeService.Delete(id);

            return RedirectToAction("GetOffices");
        }


        //-------------- UPDATE OFFICE -----------------//
        [HttpGet]
        public IActionResult UpdateOffice(int id)
        {
            var office = _officeService.GetOfficeById(id);

            OfficeDto newOfficeDto = new OfficeDto
            {
                Description = office.Description
            };

            return View(newOfficeDto);
        }

        [HttpPost]
        public IActionResult UpdateOffice(int id, OfficeDto dto)
        {
            _officeService.Update(id, dto);

            return RedirectToAction("GetOffices");
        }
    }
}

src/BoilerPlateExample.Web/Views/Office/CreateOffice.cshtml
@model BoilerPlateExample.Dto.OfficeDto

@{
    ViewBag.Title = "Create new office";
}

<h3>@ViewBag.Title</h3>

<form action="" method="post">
    
    @Html.LabelFor(x => x.Description, "Description:")
    @Html.EditorFor(x => x.Description)

    <input type="submit" value="Create Office" />

</form>

src/BoilerPlateExample.Web/Views/Office/GetOffice.cshtml
@model BoilerPlateExample.Dto.Office.OfficeEmployeeListDto

@{
    ViewBag.Title = "Office Details";
}

<h3>@ViewBag.Title</h3>

@if (Model != null)
{
<h4>@Model.Description</h4>
    <br />
    foreach (var employee in @Model.Employees)
    {
    <p>
        @employee.FirstName&nbsp;@employee.LastName
    </p>
        <br />
    }

}
else
{
    <form action="" method="get">

        @Html.LabelFor(x => x.Id)
        &nbsp;
        @Html.TextBoxFor(x => x.Id)
        <br />
        <input type="submit" value="Get Office" />

    </form>
}

src/BoilerPlateExample.Web/Views/Office/GetOffices.cshtml
@model BoilerPlateExample.Dto.OfficeListDto

@{
    ViewBag.Title = "List of offices";
}

<h3>@ViewBag.Title</h3>

@foreach (var office in Model.Offices)
{
    <div>
        @office.Id
        <br />
        @office.Description
        <br />
        @*@using (Html.BeginForm("UpdateOffice", "Office", new { id = office.Id })) {<button type="submit" name="Update" onclick=</button>}*@
        @Html.ActionLink("Update", "UpdateOffice", new { id = office.Id })
        &nbsp;
        @Html.ActionLink("Details", "GetOffice", new { id = office.Id })
        <br/>
        @using (Html.BeginForm("DeleteOffice", "Office", new { id = office.Id }))
        {<button type="submit" name="Delete" onclick="return confirm('Are you sure you want to delete this office?')" value="Delete">Delete</button>}
        <br />
    </div>
}

<h4>
    @Html.ActionLink("Add New", "CreateOffice")
</h4>

src/BoilerPlateExample.Web/Views/Office/UpdateOffice.cshtml
@model BoilerPlateExample.Dto.OfficeDto

@{
    ViewBag.Title = "Change Office Name";
}

<h3>@ViewBag.Title</h3>

<form action="" method="post">

    @Html.HiddenFor(x => x.Id)
    <br />
    @Html.LabelFor(x => x.Description, "Description:")
    &nbsp;
    @Html.EditorFor(x => x.Description)
    <br/>
    <input type="submit" value="Update Office" />

</form>